const i18Obj = {
  'en': {
    'tilda': '`', // 1 row
    'q': 'q', // 2 row
    'w': 'w',
    'e': 'e',
    'r': 'r',
    't': 't',
    'y': 'y',
    'u': 'u',
    'i': 'i',
    'o': 'o',
    'p': 'p',
    'squareQuoteLeft': '[',
    'squareQuoteRight': ']',
    'a': 'a', // 3 row
    's': 's',
    'd': 'd',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'semicolon': ';',
    'singleQuote': "'",
    'z': 'z', // 4 row
    'x': 'x',
    'c': 'c',
    'v': 'v',
    'b': 'b',
    'n': 'n',
    'm': 'm',
    'comma': ',',
    'point': '.',
		'Backspace': 'Backspace',
		'Tab': 'Tab',
		'Delete': 'Del',
		'CapsLock': 'Caps Lock',
		'Enter': 'Enter',
		'Shift': 'Shift',
		'Control': 'Ctrl',
		'Meta': 'Win',
		'ArrowUp': '🠕',
		'ArrowLeft': '🠔',
		'ArrowDown': '🠗',
		'ArrowRight': '🠖',
		'Alt': 'Alt',
		' ': '&nbsp;&nbsp;',
		'1': '1',
		'2': '2',
		'3': '3',
		'4': '4',
		'5': '5',
		'6': '6',
		'7': '7',
		'8': '8',
		'9': '9',
		'0': '0',
		'-': '-',
		'=': '=',
		'Slash': '/',
		'SlashBack': '\\',
  },
  'ru': {
		'tilda': 'ё', // 1 row
    'q': 'й', // 2 row
    'w': 'ц',
    'e': 'у',
    'r': 'к',
    't': 'е',
    'y': 'н',
    'u': 'г',
    'i': 'ш',
    'o': 'щ',
    'p': 'з',
    'squareQuoteLeft': 'х',
    'squareQuoteRight': 'ъ',
    'a': 'ф', // 3 row
    's': 'ы',
    'd': 'в',
    'f': 'а',
    'g': 'п',
    'h': 'р',
    'j': 'о',
    'k': 'л',
    'l': 'д',
    'semicolon': 'ж',
    'singleQuote': "э",
    'z': 'я', // 4 row
    'x': 'ч',
    'c': 'с',
    'v': 'м',
    'b': 'и',
    'n': 'т',
    'm': 'ь',
    'comma': 'б',
    'point': 'ю',
		'Backspace': 'Backspace',
		'Tab': 'Tab',
		'Delete': 'Del',
		'CapsLock': 'Caps Lock',
		'Enter': 'Enter',
		'Shift': 'Shift',
		'Control': 'Ctrl',
		'Meta': 'Win',
		'ArrowUp': '🠕',
		'ArrowLeft': '🠔',
		'ArrowDown': '🠗',
		'ArrowRight': '🠖',
		'Alt': 'Alt',
		' ': '&nbsp;&nbsp;',
		'1': '1',
		'2': '2',
		'3': '3',
		'4': '4',
		'5': '5',
		'6': '6',
		'7': '7',
		'8': '8',
		'9': '9',
		'0': '0',
		'-': '-',
		'=': '=',
		'Slash': '/',
		'SlashBack': '\\',
  }
}
export default i18Obj;
